version: '2'

services:
  ctfd:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - UPLOAD_FOLDER=/var/lib/CTFd/uploads
      - ACCESS_LOG=/var/log/CTFd/access.log
      - ERROR_LOG=/var/log/CTFd/error.log
      - WORKERS=4
    volumes:
      - .:/opt/CTFd
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/lib/CTFd/uploads
    depends_on:
      - db

  db:
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
